// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	publicapi "github.com/walletera/payments-types/publicapi"
)

// Mocksecurity_source_publicapi is an autogenerated mock type for the SecuritySource type
type Mocksecurity_source_publicapi struct {
	mock.Mock
}

type Mocksecurity_source_publicapi_Expecter struct {
	mock *mock.Mock
}

func (_m *Mocksecurity_source_publicapi) EXPECT() *Mocksecurity_source_publicapi_Expecter {
	return &Mocksecurity_source_publicapi_Expecter{mock: &_m.Mock}
}

// BearerAuth provides a mock function with given fields: ctx, operationName
func (_m *Mocksecurity_source_publicapi) BearerAuth(ctx context.Context, operationName string) (publicapi.BearerAuth, error) {
	ret := _m.Called(ctx, operationName)

	if len(ret) == 0 {
		panic("no return value specified for BearerAuth")
	}

	var r0 publicapi.BearerAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (publicapi.BearerAuth, error)); ok {
		return rf(ctx, operationName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) publicapi.BearerAuth); ok {
		r0 = rf(ctx, operationName)
	} else {
		r0 = ret.Get(0).(publicapi.BearerAuth)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, operationName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mocksecurity_source_publicapi_BearerAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BearerAuth'
type Mocksecurity_source_publicapi_BearerAuth_Call struct {
	*mock.Call
}

// BearerAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - operationName string
func (_e *Mocksecurity_source_publicapi_Expecter) BearerAuth(ctx interface{}, operationName interface{}) *Mocksecurity_source_publicapi_BearerAuth_Call {
	return &Mocksecurity_source_publicapi_BearerAuth_Call{Call: _e.mock.On("BearerAuth", ctx, operationName)}
}

func (_c *Mocksecurity_source_publicapi_BearerAuth_Call) Run(run func(ctx context.Context, operationName string)) *Mocksecurity_source_publicapi_BearerAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Mocksecurity_source_publicapi_BearerAuth_Call) Return(_a0 publicapi.BearerAuth, _a1 error) *Mocksecurity_source_publicapi_BearerAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mocksecurity_source_publicapi_BearerAuth_Call) RunAndReturn(run func(context.Context, string) (publicapi.BearerAuth, error)) *Mocksecurity_source_publicapi_BearerAuth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocksecurity_source_publicapi creates a new instance of Mocksecurity_source_publicapi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksecurity_source_publicapi(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mocksecurity_source_publicapi {
	mock := &Mocksecurity_source_publicapi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
