// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	publicapi "github.com/walletera/payments-types/publicapi"
)

// Mockhandler_publicapi is an autogenerated mock type for the Handler type
type Mockhandler_publicapi struct {
	mock.Mock
}

type Mockhandler_publicapi_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockhandler_publicapi) EXPECT() *Mockhandler_publicapi_Expecter {
	return &Mockhandler_publicapi_Expecter{mock: &_m.Mock}
}

// GetPayment provides a mock function with given fields: ctx, params
func (_m *Mockhandler_publicapi) GetPayment(ctx context.Context, params publicapi.GetPaymentParams) (publicapi.GetPaymentRes, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 publicapi.GetPaymentRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, publicapi.GetPaymentParams) (publicapi.GetPaymentRes, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, publicapi.GetPaymentParams) publicapi.GetPaymentRes); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publicapi.GetPaymentRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, publicapi.GetPaymentParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockhandler_publicapi_GetPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayment'
type Mockhandler_publicapi_GetPayment_Call struct {
	*mock.Call
}

// GetPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - params publicapi.GetPaymentParams
func (_e *Mockhandler_publicapi_Expecter) GetPayment(ctx interface{}, params interface{}) *Mockhandler_publicapi_GetPayment_Call {
	return &Mockhandler_publicapi_GetPayment_Call{Call: _e.mock.On("GetPayment", ctx, params)}
}

func (_c *Mockhandler_publicapi_GetPayment_Call) Run(run func(ctx context.Context, params publicapi.GetPaymentParams)) *Mockhandler_publicapi_GetPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(publicapi.GetPaymentParams))
	})
	return _c
}

func (_c *Mockhandler_publicapi_GetPayment_Call) Return(_a0 publicapi.GetPaymentRes, _a1 error) *Mockhandler_publicapi_GetPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockhandler_publicapi_GetPayment_Call) RunAndReturn(run func(context.Context, publicapi.GetPaymentParams) (publicapi.GetPaymentRes, error)) *Mockhandler_publicapi_GetPayment_Call {
	_c.Call.Return(run)
	return _c
}

// ListPayments provides a mock function with given fields: ctx, params
func (_m *Mockhandler_publicapi) ListPayments(ctx context.Context, params publicapi.ListPaymentsParams) (publicapi.ListPaymentsRes, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPayments")
	}

	var r0 publicapi.ListPaymentsRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, publicapi.ListPaymentsParams) (publicapi.ListPaymentsRes, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, publicapi.ListPaymentsParams) publicapi.ListPaymentsRes); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publicapi.ListPaymentsRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, publicapi.ListPaymentsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockhandler_publicapi_ListPayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPayments'
type Mockhandler_publicapi_ListPayments_Call struct {
	*mock.Call
}

// ListPayments is a helper method to define mock.On call
//   - ctx context.Context
//   - params publicapi.ListPaymentsParams
func (_e *Mockhandler_publicapi_Expecter) ListPayments(ctx interface{}, params interface{}) *Mockhandler_publicapi_ListPayments_Call {
	return &Mockhandler_publicapi_ListPayments_Call{Call: _e.mock.On("ListPayments", ctx, params)}
}

func (_c *Mockhandler_publicapi_ListPayments_Call) Run(run func(ctx context.Context, params publicapi.ListPaymentsParams)) *Mockhandler_publicapi_ListPayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(publicapi.ListPaymentsParams))
	})
	return _c
}

func (_c *Mockhandler_publicapi_ListPayments_Call) Return(_a0 publicapi.ListPaymentsRes, _a1 error) *Mockhandler_publicapi_ListPayments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockhandler_publicapi_ListPayments_Call) RunAndReturn(run func(context.Context, publicapi.ListPaymentsParams) (publicapi.ListPaymentsRes, error)) *Mockhandler_publicapi_ListPayments_Call {
	_c.Call.Return(run)
	return _c
}

// PostPayment provides a mock function with given fields: ctx, req, params
func (_m *Mockhandler_publicapi) PostPayment(ctx context.Context, req *publicapi.PostPaymentReq, params publicapi.PostPaymentParams) (publicapi.PostPaymentRes, error) {
	ret := _m.Called(ctx, req, params)

	if len(ret) == 0 {
		panic("no return value specified for PostPayment")
	}

	var r0 publicapi.PostPaymentRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *publicapi.PostPaymentReq, publicapi.PostPaymentParams) (publicapi.PostPaymentRes, error)); ok {
		return rf(ctx, req, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *publicapi.PostPaymentReq, publicapi.PostPaymentParams) publicapi.PostPaymentRes); ok {
		r0 = rf(ctx, req, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publicapi.PostPaymentRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *publicapi.PostPaymentReq, publicapi.PostPaymentParams) error); ok {
		r1 = rf(ctx, req, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockhandler_publicapi_PostPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostPayment'
type Mockhandler_publicapi_PostPayment_Call struct {
	*mock.Call
}

// PostPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - req *publicapi.PostPaymentReq
//   - params publicapi.PostPaymentParams
func (_e *Mockhandler_publicapi_Expecter) PostPayment(ctx interface{}, req interface{}, params interface{}) *Mockhandler_publicapi_PostPayment_Call {
	return &Mockhandler_publicapi_PostPayment_Call{Call: _e.mock.On("PostPayment", ctx, req, params)}
}

func (_c *Mockhandler_publicapi_PostPayment_Call) Run(run func(ctx context.Context, req *publicapi.PostPaymentReq, params publicapi.PostPaymentParams)) *Mockhandler_publicapi_PostPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*publicapi.PostPaymentReq), args[2].(publicapi.PostPaymentParams))
	})
	return _c
}

func (_c *Mockhandler_publicapi_PostPayment_Call) Return(_a0 publicapi.PostPaymentRes, _a1 error) *Mockhandler_publicapi_PostPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockhandler_publicapi_PostPayment_Call) RunAndReturn(run func(context.Context, *publicapi.PostPaymentReq, publicapi.PostPaymentParams) (publicapi.PostPaymentRes, error)) *Mockhandler_publicapi_PostPayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockhandler_publicapi creates a new instance of Mockhandler_publicapi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockhandler_publicapi(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockhandler_publicapi {
	mock := &Mockhandler_publicapi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
