// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	publicapi "github.com/walletera/payments-types/publicapi"
)

// Mocksecurity_handler_publicapi is an autogenerated mock type for the SecurityHandler type
type Mocksecurity_handler_publicapi struct {
	mock.Mock
}

type Mocksecurity_handler_publicapi_Expecter struct {
	mock *mock.Mock
}

func (_m *Mocksecurity_handler_publicapi) EXPECT() *Mocksecurity_handler_publicapi_Expecter {
	return &Mocksecurity_handler_publicapi_Expecter{mock: &_m.Mock}
}

// HandleBearerAuth provides a mock function with given fields: ctx, operationName, t
func (_m *Mocksecurity_handler_publicapi) HandleBearerAuth(ctx context.Context, operationName string, t publicapi.BearerAuth) (context.Context, error) {
	ret := _m.Called(ctx, operationName, t)

	if len(ret) == 0 {
		panic("no return value specified for HandleBearerAuth")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, publicapi.BearerAuth) (context.Context, error)); ok {
		return rf(ctx, operationName, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, publicapi.BearerAuth) context.Context); ok {
		r0 = rf(ctx, operationName, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, publicapi.BearerAuth) error); ok {
		r1 = rf(ctx, operationName, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mocksecurity_handler_publicapi_HandleBearerAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleBearerAuth'
type Mocksecurity_handler_publicapi_HandleBearerAuth_Call struct {
	*mock.Call
}

// HandleBearerAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - operationName string
//   - t publicapi.BearerAuth
func (_e *Mocksecurity_handler_publicapi_Expecter) HandleBearerAuth(ctx interface{}, operationName interface{}, t interface{}) *Mocksecurity_handler_publicapi_HandleBearerAuth_Call {
	return &Mocksecurity_handler_publicapi_HandleBearerAuth_Call{Call: _e.mock.On("HandleBearerAuth", ctx, operationName, t)}
}

func (_c *Mocksecurity_handler_publicapi_HandleBearerAuth_Call) Run(run func(ctx context.Context, operationName string, t publicapi.BearerAuth)) *Mocksecurity_handler_publicapi_HandleBearerAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(publicapi.BearerAuth))
	})
	return _c
}

func (_c *Mocksecurity_handler_publicapi_HandleBearerAuth_Call) Return(_a0 context.Context, _a1 error) *Mocksecurity_handler_publicapi_HandleBearerAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mocksecurity_handler_publicapi_HandleBearerAuth_Call) RunAndReturn(run func(context.Context, string, publicapi.BearerAuth) (context.Context, error)) *Mocksecurity_handler_publicapi_HandleBearerAuth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocksecurity_handler_publicapi creates a new instance of Mocksecurity_handler_publicapi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksecurity_handler_publicapi(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mocksecurity_handler_publicapi {
	mock := &Mocksecurity_handler_publicapi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
