// Code generated by ogen, DO NOT EDIT.

package publicapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetPayment implements get-payment operation.
//
// Retrieves an individual payment.
//
// GET /payments/{paymentId}
func (UnimplementedHandler) GetPayment(ctx context.Context, params GetPaymentParams) (r GetPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostPayment implements post-payment operation.
//
// Creates a payment.
//
// POST /payments
func (UnimplementedHandler) PostPayment(ctx context.Context, req *PostPaymentReq, params PostPaymentParams) (r PostPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}
