// Code generated by ogen, DO NOT EDIT.

package publicapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetPaymentOperation   OperationName = "GetPayment"
	ListPaymentsOperation OperationName = "ListPayments"
	PostPaymentOperation  OperationName = "PostPayment"
)
