// Code generated by ogen, DO NOT EDIT.
package publicapi

type GetPaymentRes interface {
	getPaymentRes()
}

type ListPaymentsRes interface {
	listPaymentsRes()
}

type PostPaymentRes interface {
	postPaymentRes()
}
