// Code generated by ogen, DO NOT EDIT.
package privateapi

type GetPaymentRes interface {
	getPaymentRes()
}

type PatchPaymentRes interface {
	patchPaymentRes()
}

type PostPaymentRes interface {
	postPaymentRes()
}
