// Code generated by ogen, DO NOT EDIT.

package privateapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetPaymentOperation   OperationName = "GetPayment"
	PatchPaymentOperation OperationName = "PatchPayment"
	PostPaymentOperation  OperationName = "PostPayment"
)
