dir: tests
outpkg: tests
filename: "mock_{{.InterfaceNameSnake}}.go"
packages:
  github.com/walletera/payments-types/api:
    interfaces:
        Handler:
          config:
            with-expecter: true
        SecurityHandler:
          config:
            with-expecter: true
        SecuritySource:
          config:
            with-expecter: true