openapi: "3.0.0"

info:
  title: "Payments Private API"
  description: "API to create and update payments on the payments service"
  version: "1.0.0"

paths:
  /payments/{paymentId}:
    get:
      description: "Retrieves an individual payment"
      operationId: "get-payment"
      parameters:
        - name: "paymentId"
          in: "path"
          description: "Payment Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Payment found"
          content:
            application/json:
              schema:
                $ref: "payment.yaml#/components/schemas/payment"
        "401":
          description: "Unauthorized"
        "404":
          description: "Payment not found"
        "500":
          description: "Internal error"

    patch:
      summary: "Updates an outbound payment"
      operationId: "patch-payment"
      parameters:
        - name: "X-Walletera-Correlation-Id"
          in: "header"
          description: "a UUID that allows to trace end-to-end transactions"
          required: false
          schema:
            type: string
            format: "uuid"
        - name: "paymentId"
          in: "path"
          description: "Payment Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "payment.yaml#/components/schemas/paymentUpdate"
      responses:
        "200":
          description: "Payment successfully updated"
        "400":
          description: "The provided parameters are incorrect"
          content:
            application/json:
              schema:
                $ref: "api-error.yaml#/components/schemas/apiError"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: "api-error.yaml#/components/schemas/apiError"

  /payments:
    post:
      summary: "Creates a payment"
      operationId: "post-payment"
      tags:
        - private
      parameters:
        - name: "X-Walletera-Correlation-Id"
          in: "header"
          description: "a UUID that allows to trace end-to-end transactions"
          required: false
          schema:
            type: string
            format: "uuid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: "Payment creation request body"
              allOf:
                - $ref: "payment.yaml#/components/schemas/paymentBasicAttributes"
                - $ref: "payment.yaml#/components/schemas/paymentExtraAttributes"
      responses:
        "201":
          description: "Payment successfully created"
          content:
            application/json:
              schema:
                $ref: "payment.yaml#/components/schemas/payment"
        "400":
          description: "The provided parameters are incorrect"
          content:
            application/json:
              schema:
                $ref: "api-error.yaml#/components/schemas/apiError"
        "401":
          description: "Unauthorized"
        "409":
          description: "The payment already exist"
          content:
            application/json:
              schema:
                $ref: "api-error.yaml#/components/schemas/apiError"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: "api-error.yaml#/components/schemas/apiError"
