openapi: "3.0.0"

components:

  schemas:
    payment:
      type: "object"
      description: "Payment type"
      properties:
        id:
          type: "string"
          format: "uuid"
          description: "Payment id"
        amount:
          type: "number"
          format: "double"
          description: "Payment amount"
        currency:
          type: "string"
          description: "Payment currency"
        direction:
          type: "string"
          enum: [ "inbound", "outbound" ]
        customerId:
          type: "string"
          format: "uuid"
          description: "The customer that sent or received the payment"
        externalId:
          type: "string"
          description: "Id assigned to the operation by an external payment provider"
        schemeId:
          type: "string"
          description: "Id assigned to the operation by the payment scheme or clearing institution"
        beneficiary:
          $ref: "#/components/schemas/accountDetails"
        debtor:
          $ref: "#/components/schemas/accountDetails"
        status:
          $ref: "#/components/schemas/paymentStatus"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
      required:
        - "id"
        - "amount"
        - "currency"

    accountDetails:
      type: "object"
      description: "bank account details"
      properties:
        institutionName:
          type: string
        institutionId:
          type: string
        currency:
          type: string
        accountType:
          type: string
          enum:
            - cvu
            - dinopay
        accountDetails:
          description: "Extra account details. The details depend on the accountType."
          type: object
          oneOf:
            - $ref: "#/components/schemas/cvuAccountDetails"
            - $ref: "#/components/schemas/dinopayAccountDetails"

    cvuAccountDetails:
      type: object
      properties:
        cuit:
          description: "Account owner national identification number"
          type: string
          pattern: '^\d{11}$'
        cvu:
          type: string
          pattern: '^\d{22}$'
        alias:
          type: string

    dinopayAccountDetails:
      type: object
      properties:
        accountHolder:
          type: "string"
          description: "Name of the owner of the account"
        accountNumber:
          type: "string"
          description: "Account number on DinoPay"
      required:
        - "accountHolder"
        - "accountNumber"

    paymentUpdate:
      type: "object"
      description: "Body of the PATH /withdrawal request"
      properties:
        paymentId:
          type: "string"
          format: "uuid"
          description: "Payment Id"
        externalId:
          type: "string"
          description: "Id assigned to the operation by the external payment provider"
        status:
          type: "string"
          $ref: "#/components/schemas/paymentStatus"
          description: "Payment status"
      required:
        - "paymentId"
        - "status"

    paymentStatus:
      type: string
      enum: [ "pending", "delivered", "confirmed", "failed", "rejected" ]

    apiError:
      type: "object"
      description: "Body of the error responses"
      properties:
        errorMessage:
          type: "string"
          description: "A message describing the error"
        errorCode:
          type: "string"
          format: "uuid"
          description: "A unique identifier for the specific error"
      required:
        - "errorMessage"
        - "errorCode"
