package wogen

import (
    "github.com/go-faster/jx"
    "github.com/ogen-go/ogen/json"
)

// SerializationWrapper fixes issues when serializing
// models generated by the openapi generator (ogen)
type SerializationWrapper struct {
    marshaller json.Marshaler
}

func NewSerializationWrapper(marshaller json.Marshaler) *SerializationWrapper {
    return &SerializationWrapper{marshaller: marshaller}
}

func (s SerializationWrapper) MarshalJSON() ([]byte, error) {
    e := jx.Encoder{}
    s.marshaller.Encode(&e)
    return e.Bytes(), nil
}
