// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// PatchPayment implements patchPayment operation.
//
// Patches an outbound payment.
//
// PATCH /payments/{paymentId}
func (UnimplementedHandler) PatchPayment(ctx context.Context, req *PaymentPatchBody, params PatchPaymentParams) (r PatchPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostPayment implements postPayment operation.
//
// Creates a payment.
//
// POST /payments
func (UnimplementedHandler) PostPayment(ctx context.Context, req *Payment) (r PostPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}
